### ISSUE TITLE
Feature Req: Allow creation of 'table-less' classes within the config.json file

### ISSUE THREAD

**Issue by digitalpenguin** [theboxer/Git-Package-Management#105]
I've been working on an extra that has an xPDO schema containing a kind of abstract object that other objects extend. I'll include the schema for reference.

`<?xml version="1.0" encoding="UTF-8"?>
<model package="modtimetable" baseClass="xPDOObject" platform="mysql" defaultEngine="MyISAM" phpdoc-package="modtimetable" version="1.1">
    <object class="modTimetableObject" extends="xPDOSimpleObject">
        <field key="name" dbtype="varchar" precision="100" phptype="string" null="false" default="" />
        <field key="description" dbtype="text" phptype="text" null="false" default="" />
        <field key="image" dbtype="text" phptype="string" null="true" />
        <field key="active" dbtype="tinyint" precision="1" phptype="integer" null="true"/>
        <field key="position" dbtype="int" precision="10" phptype="integer" null="true"/>
        <composite alias="ExtraFieldClosure" class="modTimetableExtraFieldClosure" local="id" foreign="object_id" cardinality="many" owner="local" />
    </object>
    <object class="modTimetableTimetable" table="modtimetable_timetables" extends="modTimetableObject">
        <composite alias="TimetableDay" class="modTimetableDay" local="id" foreign="timetable_id" cardinality="many" owner="local" />
    </object>
    <object class="modTimetableDay" table="modtimetable_days" extends="modTimetableObject">
        <field key="timetable_id" dbtype="int" precision="10" phptype="integer" null="false"/>
        <aggregate alias="TimetableTimetable" class="modTimetableTimetable" local="timetable_id" foreign="id" cardinality="one" owner="foreign" />
        <composite alias="TimetableSession" class="modTimetableSession" local="id" foreign="day_id" cardinality="many" owner="local" />
    </object>
    <object class="modTimetableSession" table="modtimetable_sessions" extends="modTimetableObject">
        <field key="day_id" dbtype="int" precision="10" phptype="integer" null="false"/>
        <field key="teacher" dbtype="varchar" precision="100" phptype="string" null="true" />
        <field key="start_time" dbtype="varchar" precision="100" phptype="string" null="true" />
        <field key="end_time" dbtype="varchar" precision="100" phptype="string" null="true" />
        <aggregate alias="TimetableDay" class="modTimetableDay" local="day_id" foreign="id" cardinality="one" owner="foreign" />
    </object>
    <object class="modTimetableExtraFieldClosure" table="modtimetable_extra_field_closures" extends="xPDOSimpleObject">
        <field key="object_id" dbtype="int" precision="10" phptype="integer" null="false"/>
        <field key="field_id" dbtype="int" precision="10" phptype="integer" null="false"/>
        <aggregate alias="TimetableObject" class="modTimetableObject" local="object_id" foreign="id" cardinality="one" owner="foreign" />
        <aggregate alias="ExtraField" class="modTimetableExtraField" local="field_id" foreign="id" cardinality="one" owner="foreign" />
    </object>
    <object class="modTimetableExtraField" table="modtimetable_extra_fields" extends="xPDOSimpleObject">
        <field key="name" dbtype="varchar" precision="100" phptype="string" null="false" default="" />
        <composite alias="ExtraFieldClosure" class="modTimetableExtraFieldClosure" local="id" foreign="object_id" cardinality="many" owner="local" />
    </object>
</model>`

Note that modTimetableObject does not have a table="" parameter as it's not meant to have a table actually created in the database. 

In the config.json file, "modTimetableObject" must be added or GPM won't work. See:
`,"database": {
        "tables": ["modTimetableObject","modTimetableTimetable","modTimetableDay","modTimetableSession","modTimetableExtraFieldClosure","modTimetableExtraField"]
    }`

GPM assumes this means a table should be created in the database and gives an error when it cannot find the table="" parameter.

It would be good to have an option to create the classes without attempting to create the table as well.

**Comment by theboxer** [comment]
Shame I didn't notice this sooner. This is in GPM for a very long time: http://theboxer.github.io/Git-Package-Management/config/database/

You want to list those objects in `simpleObjects` array.
