### ISSUE TITLE
Invalid permissions if new_folder_permissions/new_file_permissions isn't set

### ISSUE THREAD

**Issue by Mark-H** [theboxer/Git-Package-Management#109]
MODX doesn't create the settings [used here](https://github.com/theboxer/Git-Package-Management/blob/master/core/components/gitpackagemanagement/model/gitpackagemanagement/builder/gitpackagebuilder.class.php#L143) unless a value is provided during setup. On my dev site, it seems to create files and folders with a permission of 0, making it unavailable to GPM itself.

**Comment by Jako** [comment]
```
chmod($this->builder->directory, octdec($this->modx->getOption('new_folder_permissions', null, '0775')));
```
should solve that.
