### ISSUE TITLE
Default always being set to 0 for integers

### ISSUE THREAD

**Issue by hugopeek** [theboxer/Git-Package-Management#120]
I'm trying to create integer fields in the database with default value of NULL, but it keeps switching back to 0.

This is in the schema:
```
<field key="withdraw_min" dbtype="int" precision="10" attributes="unsigned" phptype="integer" null="true" default="NULL" />
```

But this is in the map.inc.php file (in the mysql folder):
```
  array (
    'id' => NULL,
    'resource_id' => NULL,
    'withdraw_min' => 0,
    ...
  ),
```
Changing the value there to NULL creates new rows in the DB with NULL as default, but this gets overwritten every time you update the package.

**Comment by Jako** [comment]
That should be an xPDO generator issue. But you could not set null as default, then it won't be added to the map file and it is null according to a model i have in use.

**Comment by hugopeek** [comment]
Hi @Jako, thanks for your response! It's working now with your suggestion.

So for reference: using `default=""` for int fields results in a default of 0 in the MySQL model. Leave it out and add `null="true"` to get NULL as default.
