### ISSUE TITLE
[Bug] Error on add package from premature save() call

### ISSUE THREAD

**Issue by smaddock** [theboxer/Git-Package-Management#131]
/core/components/gitpackagemanagement/processors/mgr/gitpackage/create.class.php

Line 75 sets _and saves_ the GitPackage object before other required fields are set in lines 102-107. Commenting out line 154 eliminates the error, and allows the object to be saved naturally.

**Comment by Jako** [comment]
Similar to this: https://github.com/theboxer/Git-Package-Management/pull/129

**Comment by smaddock** [comment]
Closing as duplicate.
