### ISSUE TITLE
Package won't have the needed system settings

### ISSUE THREAD

**Issue by camicase82** [TheBoxer/Git-Package-Management#152]
I'm currently developing an extra using GPM, when I install the package directly from GPM, I'll get the following settings

![image](https://user-images.githubusercontent.com/8999046/141492554-9f47e3a4-61b8-4664-ac01-898d0c1d171e.png)

Which I'll use in my code like this:

`$assetsLocation = $this->modx->getOption('kraken.assets_path');`

But when I generate the package and install it as a normal extra, these settings would not be part of Modx, what I'm doing wrong?

**Comment by hugopeek** [comment]
Hi @camicase82,

What you're observing is correct: those settings are for development purposes only. Inside the generated package, the assets and core path have moved to the 'kraken' namespace.

To access them correctly in your code, try this:

```
$assetsLocation = $this->modx->getOption('kraken.assets_path', null, $modx->getOption('assets_path') . 'components/kraken/');
```

The third argument is the default, which will be used if the first one can't be found. Essentially, the assets location is always 'assets/components/yourpackage' for generated packages. And same logic applies to core path.

**Comment by camicase82** [comment]
Thanks a lot for your response, I was already doing something wrong, which is adding the setting to the json and having dev and prod versions, will check your advice then I'll close the ticket
