### ISSUE TITLE
[branch for-3] Updating package with plugin events generates Fatal error

### ISSUE THREAD

**Issue by Bruno17** [TheBoxer/Git-Package-Management#154]
when trying to update a package with plugin events, I'm getting

PHP Fatal error:  Uncaught Error: Object of class GPM\Config\Parts\Element\PluginEvent could not be converted to string in XXX/packages/Git-Package-Management/core/components/gpm/src/Config/Rules.php:147

is this a known issue?

**Comment by matdave** [comment]
I've seen this show up, but it hasn't appeared to affect anything.

**Comment by theboxer** [comment]
this should be fixed
