### ISSUE TITLE
TVs - don't work?!

### ISSUE THREAD

**Issue by timo-schlotmann** [TheBoxer/Git-Package-Management#158]
Hey theboxer,

after the first upgrades from modx 2 to 3, I noticed that template variables don't work or am I too stupid? I can't find anything about it in the code. Are TVs coming back soon? This opportunity is very very important for us...

**Comment by JoshuaLuckers** [comment]
It looks like TV support is missing in the new version of GPM.. I guess @theboxer can confirm this. I would love to see this functionality back.

**Comment by timo-schlotmann** [comment]
Hello @JoshuaLuckers and hello @theboxer

we use the opportunity in many projects, so it is very important for us. That's why we added this feature to GPM. We tried to stick to the structure of GPM. There are definitely a few more lines that need to be adjusted, but maybe it will help.

@theboxer: If you want I can send you the source code and you prepare it for the next version?!

**Comment by JoshuaLuckers** [comment]
@timo-drescher you should be able to submit a pull request with your changes!

**Comment by JoshuaLuckers** [comment]
@timo-drescher question, how do you define templates for 3.x in GPM? I can't get mine to work :(

**Comment by timo-schlotmann** [comment]
Take a look at the conversation from https://github.com/theboxer/Git-Package-Management/pull/159
