### ISSUE TITLE
Enable remote debug snippet/plugin code

### ISSUE THREAD

**Issue by Jako** [TheBoxer/Git-Package-Management#17]
In that case it would be better to change the elementObject since static code is not remote debuggable:

```
$elementObject->set('snippet', 'return include(' . $this->modx->getOption($this->newConfig->getLowCaseName() . '.core_path') . 'elements/' . $configType . '/' . $element->getFile() . ');');
```

Almost the same for plugin code.
```
$elementObject->set('plugincode', 'include(' . $this->modx->getOption($this->newConfig->getLowCaseName() . '.core_path') . 'elements/' . $configType . '/' . $element->getFile() . ');');
```

Thanks for the nice package!

**Comment by TheBoxer** [comment]
This will result having two different setups while installing via GPM and when installing as a package. I'd like to keep it same.

You can debug snippets & plugins, just add breakpoints into the cached file in modx/core/cache/includes/elemets/...

**Comment by Jako** [comment]
Would you accept a switch with a enable_debug setting?

I often work remote on a different host (not localhost) and so I would have to sync two files (code and cached code) during debug with your proposal.

**Comment by TheBoxer** [comment]
Sure :)

I suppose it will need to be some switch for extras, maybe from context menu or something like that. What do you think?

Any other ideas what debug mode should do?

**Comment by Jako** [comment]
I thought about a simple MODX system setting. Not a package specific one.

**Comment by TheBoxer** [comment]
The system setting might be a problem, because when you switch it from false to true, it can't change your snippet code (it will remain as static and you need to make it non-static and include the php file).

So you would have to change the setting and then install/update the package, so I thought enabling/disabling debug mode per package might be better.

**Comment by Jako** [comment]
With getOption of the GitPackageManagement class, it should be easy to have a locally overwritable gitpackagemanagement.enable_debug system setting.

Another Idea for a configurable option/context menu entry (or whatever) would be an automatic creation of chunk/snippet/plugin entries in config.json. Every file in elements/xxx could create a line in config.json with that.

**Comment by Jako** [comment]
Prepared as system setting with #26
