### ISSUE TITLE
Error: Path specified for package xxx is not a valid or accessible directory …

### ISSUE THREAD

**Issue by Jako** [TheBoxer/Git-Package-Management#19]
I have switched https://github.com/Jako/formit2db to Git-Package-Management now the log is showing the error 'Path specified for package formit2db is not a valid or accessible directory …' if it does not exist.

Looking into the package shows a file called xxx.gpm.resolve.extension_package.resolver that installs formit2db as extensionPackage even if extensionPackage is set to false.

There is a bug in GitPackageConfig->parseConfig that causes this issue.

**Comment by Jako** [comment]
Removing the extensionPackage lines in config.json or setting extensionPackage to null removes that issue too.

**Comment by TheBoxer** [comment]
The intended behaviour is, if you have `extensionPackage: {}` in config, you want to add extension package with default options. So if you don't want extension package, you should not have it in config at all.

**Comment by Jako** [comment]
Could you then add a sentence in the wiki document *Creating the config* in the first section after 'All sections except the general are optional.'

'If a section is not needed/used, set it to `null` or remove it from the config.json.'

And change in the minimal config the section to `extensionPackage: null`.

**Comment by TheBoxer** [comment]
Updated, thanks!
