### ISSUE TITLE
Menus without actions in Revo 2.3

### ISSUE THREAD

**Issue by Jako** [TheBoxer/Git-Package-Management#22]
These are possible if the namespace is set according to the extra namespace in the menu. Described in http://rtfm.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/custom-manager-pages-in-2.3

```
    "menus": [
      {
        "text": "xxx.menu_yyy",
        "description": "xxx.menu_yyy_desc",
        "action": "yyy",
        "parent": "components",
        "namespace": "xxx"
      },
```

There is no need for an index controller this way. Could there be a switch inside of Git-Package-Management that makes this configurable. I.e. if menus 'namespace' is set and 'action' is not numeric.

**Comment by Jako** [comment]
Namespaced menu entries were already defined in create/update class but not in buildpackage class. Now I understand why the menu has worked fine locally :)

**Comment by TheBoxer** [comment]
Thanks :)
