### ISSUE TITLE
Remove extracted packages in _packages folder

### ISSUE THREAD

**Issue by Jako** [TheBoxer/Git-Package-Management#27]
if this is possible automatically (maybe triggered by a system setting). Would be nice.

**Comment by TheBoxer** [comment]
Why you'd like to automatically delete them?

You can easily check if it packed everything you wanted :)

But anyway, it should be possible (at least on unix like systems).

**Comment by Jako** [comment]
Normally I work remote on my development server and just don't want to sync those files. There is no rule to exclude subfolders in PhpStorm from sync as far as I see. The extracted packages are not needed after?

**Comment by TheBoxer** [comment]
Nope, they are not needed when you have the zip.

**Comment by Jako** [comment]
Possible solution added by #31
