### ISSUE TITLE
Trying to install transport package generated by GPM

### ISSUE THREAD

**Issue by Thunderofnl** [TheBoxer/Git-Package-Management#28]
Whenever I try to install a package generated by GPM it gives me these warnings/errors. I think it has something to do with the transport of the tables but I can't seem to find a solution.

Just to clarify, when I install it via git and GPM it works perfectly, just the transport package doesn't.

`PHP warning: include(/home/robin/www/modx/2.3.3/core/packages/setinputoptions-0.3.0-pl/modCategory/92880b9a40c081dcb391092e437dedb0.gpm.resolve.tables.resolver): failed to open stream: No such file or directory
PHP warning: include(): Failed opening '/home/robin/www/modx/2.3.3/core/packages/setinputoptions-0.3.0-pl/modCategory/92880b9a40c081dcb391092e437dedb0.gpm.resolve.tables.resolver' for inclusion (include_path='.:/usr/share/php:/usr/share/pear')
xPDOVehicle resolver failed: type php (/home/robin/www/modx/2.3.3/core/packages/setinputoptions-0.3.0-pl/modCategory/92880b9a40c081dcb391092e437dedb0.gpm.resolve.tables.resolver)
PHP warning: include(/home/robin/www/modx/2.3.3/core/packages/setinputoptions-0.3.0-pl/modCategory/92880b9a40c081dcb391092e437dedb0.gpm.resolve.extension_package.resolver): failed to open stream: No such file or directory
PHP warning: include(): Failed opening '/home/robin/www/modx/2.3.3/core/packages/setinputoptions-0.3.0-pl/modCategory/92880b9a40c081dcb391092e437dedb0.gpm.resolve.extension_package.resolver' for inclusion (include_path='.:/usr/share/php:/usr/share/pear')
xPDOVehicle resolver failed: type php (/home/robin/www/modx/2.3.3/core/packages/setinputoptions-0.3.0-pl/modCategory/92880b9a40c081dcb391092e437dedb0.gpm.resolve.extension_package.resolver)
Could not resolve vehicle for object of class modCategory; criteria: Array ( [category] => SetInputOptions ) `

**Comment by Jako** [comment]
Is your _build folder writable for Apache/PHP?

**Comment by Thunderofnl** [comment]
Yup, it creates the package perfectly but when I want to install the transport package via the package manager instead of GPM it gives me these results.

**Comment by TheBoxer** [comment]
Can you post here your config file and check if in your _build folder is `gpm_resolvers` subfolder and what's in it?

**Comment by Thunderofnl** [comment]
Ah there is no gpm_resolvers subfolder in it, the package was made when GPM was still on version 0.7.1 is there a way to resolve this?

The configs:

```
{
    "name": "SetInputOptions",
    "lowCaseName": "setinputoptions",
    "description": "",
    "author": "Robin",
    "version": "0.3.0",
    "package":{
        "actions": [{
            "id": 1
            ,"controller": "index"
        }],
        "menus": [{
            "text": "setinputoptions.menu.setinputoptions"
            ,"description": "setinputoptions.menu.setinputoptions_desc"
            ,"action": 1
        }],
        
        "elements": {
            "plugins": [],
            "snippets": [{
                "name": "getInputOptions"
            }],
            "chunks": [
            
            {
                "name": "inputOptionsRow"
            }
            
            ],
            "templates": [],
            "tvs": []
        },
        "systemSettings": []
    },
    
    "database": {
        "tables": ["SetInputOptionsGroup", "SetInputOptionsInputOption"]
    },
    
    "extensionPackage": {}
}

**Comment by TheBoxer** [comment]
Update GPM to latest version, try to build the package again.

If you will not see the gpm_resolvers folder, create it and set permissions so php/apache/whatever can write to it. Build package again and check if there are any files in the gpm_resolvers folder.

**Comment by Thunderofnl** [comment]
And that fixed the issue! Thank you @TheBoxer and @Jako awesome extra!

**Comment by TheBoxer** [comment]
make sure your _build folder is writable, as GPM will need to create there subfolders & files in order to build the package correctly

**Comment by Jako** [comment]
The model/{packagename} folder has to be writable too if you want to create classes from the xPDO schema.

Should go into documentation.

**Comment by TheBoxer** [comment]
Docs updated: https://github.com/TheBoxer/Git-Package-Management/wiki/Installation
