### ISSUE TITLE
Nested json config files

### ISSUE THREAD

**Issue by Jako** [TheBoxer/Git-Package-Management#35]
An idea, as an option to avoid very long config files and if it is not against other build config conventions: If a section/subsection contains a string instead of an array/object, the string points to an external file. I.E 

```
,"elements": {
    "plugins": "PackagePlugins"
}
```

PackagePlugins would point to `plugins_packageplugins.json` or maybe simpler just `packageplugins.json`

or
```
,"elements": {
    "plugins": "PackagePlugin"[{
        "PackagePlugin1"
        ,"PackagePlugin2"
    }]
}
```

PackagePlugin1 would point to `plugin_packageplugin1.json`/`packageplugin1.json`,
PackagePlugin2 would point to `plugin_packageplugin2.json`/`packageplugin2.json`.

Should be flexible enough in my opinion.

**Comment by TheBoxer** [comment]
I am planning to add some auto generating methods for config and don't very fit with my plans :)

The idea behind config was that it's single file and you don't have to update dozens of them...

**Comment by Jako** [comment]
Both ways should not touch each other.
