### ISSUE TITLE
Fast build & publish packages

### ISSUE THREAD

**Issue by Jako** [theboxer/Git-Package-Management#39]
Maybe you are interested in that branch https://github.com/Jako/Git-Package-Management/tree/feature/publish

Could be used with that basic package provider: https://github.com/Jako/modx-package-provider

**Comment by TheBoxer** [comment]
That's a cool feature for sure!
I am not sure if it should be merged to master, but at least you can add that to the readme?

**Comment by Jako** [comment]
The package provider code is too specific for master branch. 

But it would be nice to have a system setting with 'text' + 'handler' (or 'text + handler parameter) configurable with a json to avoid patching the widget javascript.

The combination of GPM + Provider is a very fast rollout possibility for me to my clients.

**Comment by TheBoxer** [comment]
I am not sure if you can do anything just with that setting, you still will need a custom javascript and processors to handle that. I see as a better option leave that in your branch and adding some info to readme (and to docs if you want).

**Comment by Jako** [comment]
The buildPackagePublish method uses the same code as buildPackage. It only has a different action. And the buildpackagepublish processor just extends the buildpackage processor by a few lines.

I just thought about a possibility to extend the package somehow by an extra class in a second package that inserts the menu and calls buildPackage method with a parameter that points to an action in the second package. Maybe a bit overkill than just patching the script.
