### ISSUE TITLE
Resources missing in transport package

### ISSUE THREAD

**Issue by Jako** [TheBoxer/Git-Package-Management#40]
Resources are created with 'create' processor but not installed with the transport package. The vehicle file does not contain them as far as I see.

This is the code for the section in 'package' section:
```
    "resources": [
      {
        "pagetitle": "XXX",
        "alias": "xxx",
        "content": "[[!FormIt?\n…\n]]\n[[$tplForm]]",
        "template": "Reporting",
        "published": 1,
        "hidemenu": 1,
        "richtext": 0,
        "parent": 0
      },

```

**Comment by TheBoxer** [comment]
It should be possible now, forgot to push :)

**Comment by Jako** [comment]
Thanks. Will try that next time.

**Comment by bartholomej** [comment]
Thx!  I'll try it tomorrow ;)

**Comment by bartholomej** [comment]
It works! Thanks.
