### ISSUE TITLE
TV Template Access settings are being reset on update

### ISSUE THREAD

**Issue by hugopeek** [theboxer/Git-Package-Management#62]
When adding TV's to an install using GPM without any templates defined in the Templates property, and you assign these TV's manually to the templates of choice, these settings get reset if you update the package. So in other words: all GPM TV's will be detached again from any template you manually assigned.

Is this expected behaviour? And is there any way to prevent this from occurring?

**Comment by theboxer** [comment]
Yes, it's expected behaviour, specify templates in the config.

**Comment by hugopeek** [comment]
Ok, thanks.
