### ISSUE TITLE
[Feature] Integrate generator-bxrextra / bxrextra into GPM

### ISSUE THREAD

**Issue by joeke** [theboxer/Git-Package-Management#72]
My current workflow for creating new MODX cmp's is to first create it the basic cmp with generator-bxrextra, and then adding it in GPM.. so I thought it would be a cool idea to integrate the generator-bxrextra functionality into GPM.
The idea here is when adding a new package in GPM, include an option to create a package from scratch, and show a basic form with the same questions as in the generator-bxrextra yeoman command line tool. This feature would also make it easier to add features to the basic bxrextra cmp, for example specifiying all the object classnames you'd like to use and creating the schema and extjs grid based on that.

If you're onboard with this, I'd be happy to create a PR for it..

**Comment by theboxer** [comment]
Yeah, I'm planning to include this feature in GPM 2

**Comment by joeke** [comment]
@theboxer Cool. If you need any help with it let me know ;)

**Comment by digitalpenguin** [comment]
+1

**Comment by theboxer** [comment]
Added for 3.x
