### ISSUE TITLE
Exclude files/folders from packaging

### ISSUE THREAD

**Issue by Jako** [theboxer/Git-Package-Management#75]
Is it possible to exclude files/folders from packaging i.e. a `assets/components/xxx/cache` folder with GPM?

**Comment by theboxer** [comment]
no, currently it's not possible

**Comment by Jako** [comment]
Is that a MODX or a GPM issue?

Von meinem iPhone gesendet

**Comment by DMeganoski** [comment]
Even though this is an old issue, I was curious myself so decided to do some digging. Here's what I found for anyone else who is curious:

It seems this is possible with modx, there are a couple options you can pass to the vehicle. 
https://forums.modx.com/thread/87671/is-it-possible-to-configure-the-build-transport-script-to-exclude-specific-files-from-packaging-in

However looking at the GPM source, it would take modifying a few files at least to implement.

If you really NEED to have certain files excluded, one suggestion in that thread that would work with GPM was to move the files before the build, then to move them back when it finished. You could use before/after resolvers to do this.

**Comment by Jako** [comment]
Solved with #112
