### ISSUE TITLE
build.config.php

### ISSUE THREAD

**Issue by davidpede** [theboxer/Git-Package-Management#80]
When adding a new package in MODX, GPM seems to be creating an empty 'build.config.php' file in the _build folder. Is this correct or a bug?

**Comment by theboxer** [comment]
This is a relic from previous versions of GPM. The build.config is no longer needed.

**Comment by Jako** [comment]
But it is still generated …

**Comment by theboxer** [comment]
Yup, someone should update the GPM :)

**Comment by Jako** [comment]
Fixed with #100

**Comment by davidpede** [comment]
Great Thanks!
