### ISSUE TITLE
Table is not created if using a hyphen in the package name

### ISSUE THREAD

**Issue by digitalpenguin** [theboxer/Git-Package-Management#94]
When adding a package to GPM on the GPM CMP, if you have used a hyphen (-) in the package name (for example when creating a base extra with the bxrextra generator) the process will stall without displaying any error on screen or in the logs.

I discovered this through a bit of trial and error. I removed the database table from the config file and then it installed fine.
I generated the package again this time without the hyphen and it all worked smoothly.

**Comment by Jako** [comment]
Don't create a package with a hyphen at least in the lowCaseName of that packge. Otherwise you will have issues with package providers like the MODX extra repository.
