### ISSUE TITLE
[Feature] Allow name and description for system settings.

### ISSUE THREAD

**Issue by digitalpenguin** [theboxer/Git-Package-Management#96]
It would be great to be able to name a system setting differently to the key and to also add a description that can be viewed within the row expander in the system settings grid.

**Comment by Jako** [comment]
It is better to use lexicons there:

```
$_lang['setting_namespace.setting_name'] = 'Title';
$_lang['setting_namespace.setting_name_desc'] = 'Description';
```

Namespace and setting_name have to be replaced with your needs.

**Comment by digitalpenguin** [comment]
OK good point. Cheers,Jako
